import { readFileSync, writeFileSync } from "node:fs";
import { expect, it } from "vitest";
import { calculateTotals, splitByItems, splitEvenly } from "../src/index.js";
import { randomCase } from "./random-case.js";

/**
 * fixtures/random.json: 300 random orders with this engine's results. The Dart port must
 * reproduce every number (packages/pricing_dart/test/random_fixtures_test.dart), which checks
 * the two engines agree far beyond the hand-worked cases.
 *
 * This test fails if the file no longer matches the engine. After an intended change to the
 * rules, regenerate with: UPDATE_FIXTURES=1 pnpm --filter @fcs/pricing test
 */
const FILE = new URL("../fixtures/random.json", import.meta.url);

function generate() {
  const cases = Array.from({ length: 300 }, (_, i) => {
    const seed = 10_001 + i;
    const { order, settings } = randomCase(seed);
    const totals = calculateTotals(order, settings);
    const ids = totals.lines.map((l) => l.id);
    const groups = [0, 1, 2].map((g) => ids.filter((_, j) => j % 3 === g)).filter((g) => g.length > 0);
    return {
      seed,
      settings,
      order,
      expected: totals,
      splitEvenly: { parts: 3, expected: splitEvenly(totals.total, 3, settings.rounding.increment) },
      splitByItems: { groups, expected: splitByItems(totals, groups, settings) },
    };
  });
  return `${JSON.stringify({ description: "Generated by packages/pricing/test/random-fixtures.test.ts. Do not edit.", cases })}\n`;
}

it("fixtures/random.json matches the engine", () => {
  const fresh = generate();
  if (process.env["UPDATE_FIXTURES"]) writeFileSync(FILE, fresh);
  expect(readFileSync(FILE, "utf8") === fresh, "fixtures/random.json is stale: run UPDATE_FIXTURES=1 pnpm --filter @fcs/pricing test").toBe(
    true,
  );
});
