import 'dart:convert';
import 'dart:io';

import 'package:fcs_pos/src/models.dart';
import 'package:fcs_pos/src/order.dart';
import 'package:fcs_pricing/fcs_pricing.dart';
import 'package:flutter_test/flutter_test.dart';

import 'fakes.dart';

/// The POS writes order events that the sync engine's order rules (packages/sync-core,
/// TypeScript) must accept. This test writes them to a shared fixture; sync-core's
/// pos-contract.test.ts replays them. Regenerate after an intended change with:
///   UPDATE_FIXTURES=1 flutter test test/contract_test.dart
const fixturePath = '../../packages/sync-core/fixtures/pos-order-events.json';

List<Map<String, dynamic>> scenario() {
  final menu = BranchMenu.fromJson(sampleMenuJson());
  MenuItem item(String id) => menu.items.firstWhere((i) => i.id == id);
  ({ModifierGroup group, ModifierOption option}) opt(String g, String o) {
    final group = menu.modifierGroups[g]!;
    return (group: group, option: group.options.firstWhere((x) => x.id == o));
  }

  var n = 0;
  String id() => '01K${(++n).toString().padLeft(23, '0')}';
  final events = <Map<String, dynamic>>[];

  // Order 1: dine-in, table 5, with modifiers, a merged quantity and a note.
  final first = OrderDraft(newId: id)
    ..setTable('5')
    ..add(item('kaphrao'), [opt('spice', 'hot'), opt('extras', 'egg')])
    ..add(item('kaphrao'), [opt('spice', 'hot'), opt('extras', 'egg')])
    ..add(item('friedrice'))
    ..add(item('thaitea'));
  first.setNote(first.lines.last, 'หวานน้อย');
  events.addAll(first.toEvents(deviceId: 'pos-1', staffId: 'staff-nok', createdAt: 1790000000000));

  // Order 2: takeaway, no table.
  final second = OrderDraft(newId: id)
    ..setOrderType(OrderType.takeaway)
    ..add(item('water'));
  events.addAll(second.toEvents(deviceId: 'pos-1', staffId: 'staff-dang', createdAt: 1790000060000));
  return events;
}

void main() {
  test('POS order events match the shared fixture replayed by the sync engine', () {
    final fresh =
        '${const JsonEncoder.withIndent('  ').convert({'description': 'Generated by apps/pos/test/contract_test.dart. Replayed by packages/sync-core/test/pos-contract.test.ts. Do not edit.', 'events': scenario()})}\n';
    final file = File(fixturePath);
    if (Platform.environment['UPDATE_FIXTURES'] != null) file.writeAsStringSync(fresh);
    expect(file.readAsStringSync(), fresh, reason: 'stale fixture: run UPDATE_FIXTURES=1 flutter test test/contract_test.dart');
  });
}
